# Dockerfile
# FROM phusion/passenger-customizable:0.9.19
FROM phusion/passenger-ruby22:0.9.19
MAINTAINER Austin Covrig "austinc@iiw.org"

# Environment variables
ENV HOME /root

# baseimage-docker's init
CMD ["/sbin/my_init"]

# Expose nginx HTTP
EXPOSE 80

# Install redis for sidekiq
RUN apt update && apt install -y redis-server libhiredis-dev && mkdir /etc/service/redis
ADD redis.sh /etc/service/redis/run
ADD redis.conf /etc/redis/redis.conf

# Enable nginx and clear default
RUN rm -f /etc/service/nginx/down /etc/nginx/sites-enabled/default

# Setup app
RUN mkdir /home/app/webapp

# Install gems
WORKDIR /tmp
ADD Gemfile /tmp
ADD Gemfile.lock /tmp
RUN bundle

# Add config
ADD webapp.conf /etc/nginx/sites-enabled/webapp.conf
ADD secret_key.conf /etc/nginx/main.d/secret_key.conf
RUN mkdir /etc/service/sidekiq
ADD sidekiq.sh /etc/service/sidekiq/run

# Add the app itself
ADD . /home/app/webapp
WORKDIR /home/app/webapp
RUN RAILS_ENV=production bundle exec rake assets:precompile
RUN chown -R app:app /home/app/webapp

# Clean up when done
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
